#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
# Make sure that your servers are configured with the right hostnames:
# [STUDENT_ID]-web-01 and [STUDENT_ID]-web-02.
sudo apt-get -y update
apt-get -y install haproxy

# editing the config file
server_config=\
"
	balance roundrobin
        server 121488-web-01 54.237.102.228 check
        server 121488-web-02 100.26.166.217 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable /etc/default/haproxy to be started by the init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
