#!/usr/bin/env bash
# Bash script that configures an ubuntu server
# localhost resolves to 127.0.0.1 and 
# facebook.com resolves to 157.240.11.35

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "157.240.11.35	facebook.com">> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
