#!/usr/bin/env bash
#Bash script that uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# Requirements:
# Only use ssh single-character flags
# You cannot use -l
ssh ubuntu@169.25.25.255 -i ~/.ssh/school
